title: Info-Robert Kingsly S

email:  srobertkingsly@gmail.com

description: >
  This website provide personal info of Mr. Robert Kingsly S

timezone: "Asia/Kolkata"
  
baseurl: "" 
url    : 

include: ['_pages']

collections:
  news:
  events:
  nptel:
  project:
  research:
  members:
    permalink: /:collection/:path/
    output: true


authors:
  denzil:
    name: Robert Kingsly S
  abhishek:
    name: Lavi
